### ISSUE TITLE
iOS font path

### ISSUE THREAD

**Issue by Klunk75** [NeriCodec/nativescript-text-justify#1]
Hi,
in your usage instructions you reported the path where to place the ttf fonts for Android only:

Usage
To establish a font type, it is necessary to create a directory assets > fonts with the fonts to be used:

Directory:
App_Resources > Android > src > main > <create paths> assets > fonts > <name>.ttf

Which is the path for iOS? I'm unable to use your plugin on iOS.
Thanks a lot!

Paolo

**Comment by NeriCodec** [comment]
Hi, I do not currently support iOS but I am already working so that I can justify the text in iOS

**Comment by alexZaicev** [comment]
Hi NeriCodec any updates on iOS plugin support? :)

**Comment by NeriCodec** [comment]
Hello @alexZaicev , I have not been very busy but can collaborate without any problem

**Comment by alexZaicev** [comment]
will the iOS support be implemented any time soon? 👍

**Comment by NeriCodec** [comment]
Not now, but you can create a directive, a copy of which I leave you here and on a label just pass the property justify

> import { Directive, ElementRef, OnInit } from "@angular/core";
> import { Label } from "tns-core-modules/ui/label";
> import { isIOS } from "tns-core-modules/ui/page/page";
> 
> const justify = require("justified");
> const platform = require("tns-core-modules/platform");
> 
> @Directive({
>     selector: "Label[justify]"
> })
> export class IsJustifyDirective implements OnInit {
>     public get nativeView(): Label {
>         return this.el.nativeElement;
>     }
> 
>     constructor(private el: ElementRef) {}
> 
>     public ngOnInit() {
>         const nativeView = this.nativeView;
> 
>         if (nativeView instanceof Label) {
>             nativeView.on(Label.loadedEvent, () => {
>                 if (isIOS) {
>                     this.nativeView.ios.textAlignment = 3;
>                 } else {
>                     // console.dir(textJustified);
>                 }
>             });
>         }
>     }
> }

**Comment by NeriCodec** [comment]
@alexZaicev Support for iOS is available...

**Comment by colosic** [comment]
Hi NeriCodec,
What is the correct implementation to use it on iOS? 
Thank you!

**Comment by nericode** [comment]
@colosic 
I have not updated the plugin but you can request a merge incorporating what I commented above, now you can generate a directive to align the text and apply it to the labes directly

**Comment by colosic** [comment]
@NeriCodec 
Thank you very much for the quick answer. I'm going to put it into practice. Thank you!
